n = int(input('Digite um valor: '))
print(f'A tabuada de {n} é: ')
print('============================')
print(f'O valor de {n} * 1  = {n}')
print(f'O valor de {n} * 2  = {n*2}')
print(f'O valor de {n} * 3  = {n*3}')
print(f'O valor de {n} * 4  = {n*4}')
print(f'O valor de {n} * 5  = {n*5}')
print(f'O valor de {n} * 6  = {n*6}')
print(f'O valor de {n} * 7  = {n*7}')
print(f'O valor de {n} * 8  = {n*8}')
print(f'O valor de {n} * 9  = {n*9}')
print(f'O valor de {n} * 10 = {n*10}')
print('============================')
